[build-system]
requires = ["setuptools>=45", "wheel", "setuptools_scm[toml]>=6.2"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["."]
exclude = ["tests", "tests.*"]

[project]
name = "torchcomp"
version = "0.2.1"
description = "Fast, efficient, and differentiable dynamic range compression/expansion/limiting for PyTorch."
readme = "README.md"
requires-python = ">=3.9"
authors = [
    {name = "Chin-Yun Yu", email = "chin-yun.yu@qmul.ac.uk"},
]
maintainers = [
    {name = "Chin-Yun Yu", email = "chin-yun.yu@qmul.ac.uk"},
]
license = {text = "MIT"}
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "torch>=2",
    "torchlpc",
    "numpy",
    "numba",
]

[project.urls]
Homepage = "https://github.com/DiffAPF/torchcomp"

